#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLS_DIR="${SCRIPT_DIR}/.build-tools"
NODE_VERSION_FILE="${SCRIPT_DIR}/.node-version"

if [ ! -f "$NODE_VERSION_FILE" ]; then
  echo "ERROR: .node-version file not found" >&2
  exit 1
fi
NODE_VERSION="$(tr -d '[:space:]' < "$NODE_VERSION_FILE")"

# ── Platform detection ────────────────────────────────────────────────────

detect_platform() {
  local os arch
  os="$(uname -s)"
  arch="$(uname -m)"

  case "$os" in
    Linux)  OS="linux" ;;
    Darwin) OS="darwin" ;;
    *)
      echo "ERROR: Unsupported OS: $os" >&2
      exit 1
      ;;
  esac

  case "$arch" in
    x86_64)       ARCH="x64" ;;
    aarch64|arm64) ARCH="arm64" ;;
    *)
      echo "ERROR: Unsupported architecture: $arch" >&2
      exit 1
      ;;
  esac
}

detect_platform

# ── Node.js ───────────────────────────────────────────────────────────────

NODE_DIR="node-v${NODE_VERSION}-${OS}-${ARCH}"
NODE_BIN_DIR="${TOOLS_DIR}/${NODE_DIR}/bin"
NODE_TARBALL="${NODE_DIR}.tar.xz"
NODE_URL="https://nodejs.org/dist/v${NODE_VERSION}/${NODE_TARBALL}"

install_node() {
  if [ -x "${NODE_BIN_DIR}/node" ]; then
    echo "Node.js ${NODE_VERSION} already installed"
    return
  fi

  echo "Downloading Node.js ${NODE_VERSION} (${OS}-${ARCH})..."
  mkdir -p "$TOOLS_DIR"
  curl -fsSL "$NODE_URL" | tar xJ -C "$TOOLS_DIR"

  if [ ! -x "${NODE_BIN_DIR}/node" ]; then
    echo "ERROR: Node.js download failed — ${NODE_BIN_DIR}/node not found" >&2
    exit 1
  fi

  echo "  Installed: ${NODE_BIN_DIR}/node"
}

validate_sea_fuse() {
  local node_bin="${NODE_BIN_DIR}/node"
  if grep -q 'NODE_SEA_FUSE' "$node_bin" 2>/dev/null; then
    echo "  NODE_SEA_FUSE sentinel: OK"
  else
    echo "ERROR: Downloaded Node.js binary is missing NODE_SEA_FUSE sentinel." >&2
    echo "       SEA builds will fail. This should not happen with official nodejs.org binaries." >&2
    exit 1
  fi
}

# ── uv (Python toolchain) ────────────────────────────────────────────────

UV_BIN_DIR="${TOOLS_DIR}/bin"

install_uv() {
  if [ -x "${UV_BIN_DIR}/uv" ]; then
    echo "uv already installed"
    return
  fi

  echo "Downloading uv..."
  mkdir -p "$UV_BIN_DIR"
  curl -LsSf https://astral.sh/uv/install.sh | \
    INSTALLER_NO_MODIFY_PATH=1 UV_INSTALL_DIR="$UV_BIN_DIR" sh 2>&1 | \
    grep -v "^$" | grep -v "^To add" | grep -v "^    source" | grep -v "^WARN:"
  echo "  Installed: ${UV_BIN_DIR}/uv"
}

# ── env.sh generation ────────────────────────────────────────────────────

write_env() {
  cat > "${TOOLS_DIR}/env.sh" << ENVEOF
# Generated by bootstrap.sh — source this to put build tools on PATH
export PATH="${NODE_BIN_DIR}:${UV_BIN_DIR}:\$PATH"
ENVEOF

  echo ""
  echo "Build tools ready:"
  echo "  node $(${NODE_BIN_DIR}/node --version)"
  echo "  npm  $(PATH="${NODE_BIN_DIR}:${PATH}" "${NODE_BIN_DIR}/npm" --version)"
  echo "  uv   $(${UV_BIN_DIR}/uv --version 2>/dev/null || echo '(version unknown)')"
}

persist_ci_path() {
  if [ -n "${GITHUB_PATH:-}" ]; then
    echo "${NODE_BIN_DIR}" >> "$GITHUB_PATH"
    echo "${UV_BIN_DIR}" >> "$GITHUB_PATH"
    echo "  (PATH entries added to \$GITHUB_PATH for subsequent CI steps)"
  fi
}

# ── Main ──────────────────────────────────────────────────────────────────

main() {
  echo "=== Abbenay Bootstrap ==="
  echo ""

  install_node
  validate_sea_fuse
  install_uv
  write_env
  persist_ci_path

  echo ""
  if [ -z "${GITHUB_PATH:-}" ]; then
    echo "Next steps:"
    echo "  source .build-tools/env.sh"
    echo "  npm install"
    echo "  node build.js"
  fi
}

main
