import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

import { getDaemonStatus, getDaemonState } from './daemon.js';
import {
  writePidFile,
  removePidFile,
  readPidFile,
  writeAddressFile,
  removeAddressFile,
  cleanupIpcArtifacts,
  ensureRuntimeDir,
} from './transport.js';
import { getPidPath } from '../core/paths.js';

const originalPlatform = process.platform;

const mockBindAsync = vi.fn();
const mockTryShutdown = vi.fn();
const mockAddService = vi.fn();

vi.mock('@grpc/grpc-js', () => {
  class MockServer {
    addService = mockAddService;
    bindAsync = mockBindAsync;
    tryShutdown = mockTryShutdown;
  }
  return {
    Server: MockServer,
    ServerCredentials: {
      createInsecure: vi.fn(() => ({ type: 'insecure' })),
      createSsl: vi.fn(() => ({ type: 'ssl' })),
    },
    loadPackageDefinition: vi.fn(() => ({
      abbenay: { v1: { Abbenay: { service: {} } } },
    })),
  };
});

vi.mock('@grpc/proto-loader', () => ({
  loadSync: vi.fn(() => ({})),
}));

vi.mock('./telemetry.js', () => ({
  initAiSdkTelemetry: vi.fn().mockResolvedValue(undefined),
}));

vi.mock('./web/server.js', () => ({
  stopEmbeddedWebServer: vi.fn().mockResolvedValue(undefined),
}));

vi.mock('./server/abbenay-service.js', () => ({
  createAbbenayService: vi.fn(() => ({})),
}));

vi.mock('./server/consumer-auth.js', () => ({
  assertConsumersConfiguredForBind: vi.fn(),
  buildConsumerAuthContext: vi.fn(() => ({ loopbackOnly: true })),
  hasConfiguredConsumers: vi.fn(() => true),
  resolveAllowOpenAuth: vi.fn(() => false),
}));

vi.mock('./grpc-tls.js', () => ({
  resolveTcpGrpcBind: vi.fn(() => ({
    tlsEnabled: false,
    serverCredentials: { type: 'insecure' },
    autoGenerated: false,
  })),
}));

describe('daemon status helpers', () => {
  let statusTmpRoot: string;

  beforeEach(() => {
    statusTmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'abbenay-daemon-status-'));
    process.env.XDG_RUNTIME_DIR = statusTmpRoot;
    removePidFile();
    cleanupIpcArtifacts();
  });

  afterEach(() => {
    removePidFile();
    cleanupIpcArtifacts();
    Object.defineProperty(process, 'platform', { value: originalPlatform });
    delete process.env.XDG_RUNTIME_DIR;
    fs.rmSync(statusTmpRoot, { recursive: true, force: true });
  });

  it('getDaemonState returns null when daemon not started in-process', () => {
    expect(getDaemonState()).toBeNull();
  });

  it('getDaemonStatus reports not running without PID', () => {
    const status = getDaemonStatus();
    expect(status.running).toBe(false);
    expect(status.pid).toBeNull();
    expect(status.socketPath).toBeTruthy();
  });

  it('getDaemonStatus reports running when PID file matches live process', () => {
    writePidFile();
    const status = getDaemonStatus();
    expect(status.running).toBe(true);
    expect(status.pid).toBe(process.pid);
  });

  it('getDaemonStatus on win32 includes address from daemon.addr', () => {
    Object.defineProperty(process, 'platform', { value: 'win32' });
    writeAddressFile('127.0.0.1', 43210);
    const status = getDaemonStatus();
    expect(status.socketPath).toBe('127.0.0.1:43210');
    expect(status.address).toBe('127.0.0.1:43210');
    removeAddressFile();
  });

  it('readPidFile returns NaN for non-numeric PID file content', () => {
    ensureRuntimeDir();
    fs.writeFileSync(getPidPath(), 'not-a-pid', { mode: 0o600 });
    expect(readPidFile()).toBeNaN();
  });
});

describe('daemon lifecycle', () => {
  let tmpRoot: string;

  beforeEach(() => {
    vi.clearAllMocks();
    tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'abbenay-daemon-test-'));
    process.env.XDG_RUNTIME_DIR = tmpRoot;
    process.env.ABBENAY_PROTO_DIR = path.resolve(import.meta.dirname, '../../../../proto');
    mockBindAsync.mockImplementation((_addr: string, _creds: unknown, cb: (err: Error | null, port?: number) => void) => {
      cb(null, 50051);
    });
    mockTryShutdown.mockImplementation((cb: () => void) => cb());
  });

  afterEach(async () => {
    const transport = await import('./transport.js');
    transport.removePidFile();
    transport.cleanupIpcArtifacts();
    Object.defineProperty(process, 'platform', { value: originalPlatform });
    delete process.env.XDG_RUNTIME_DIR;
    delete process.env.ABBENAY_PROTO_DIR;
    fs.rmSync(tmpRoot, { recursive: true, force: true });
    vi.restoreAllMocks();
  });

  it('startDaemon throws when already running', async () => {
    const transport = await import('./transport.js');
    transport.writePidFile();
    const { startDaemon } = await import('./daemon.js');
    await expect(startDaemon({ keepAlive: false })).rejects.toThrow(/already running/);
    transport.removePidFile();
  });

  it('startDaemon binds unix socket and returns state', async () => {
    Object.defineProperty(process, 'platform', { value: 'linux' });
    const { startDaemon, getDaemonState } = await import('./daemon.js');
    const state = await startDaemon({ keepAlive: false });
    expect(state).toBeTruthy();
    expect(getDaemonState()).toBe(state);
    expect(mockBindAsync).toHaveBeenCalled();
  });

  it('startDaemon binds optional TCP grpc port on unix', async () => {
    Object.defineProperty(process, 'platform', { value: 'linux' });
    const { startDaemon } = await import('./daemon.js');
    await startDaemon({ keepAlive: false, grpcPort: 50052, grpcHost: '127.0.0.1' });
    expect(mockBindAsync.mock.calls.some((c) => String(c[0]).includes('127.0.0.1:50052'))).toBe(true);
  });

  it('startDaemon cleans up on bind failure', async () => {
    Object.defineProperty(process, 'platform', { value: 'linux' });
    mockBindAsync.mockImplementationOnce((_addr: string, _creds: unknown, cb: (err: Error | null) => void) => {
      cb(new Error('bind failed'));
    });
    const { startDaemon } = await import('./daemon.js');
    await expect(startDaemon({ keepAlive: false })).rejects.toThrow('bind failed');
    const transport = await import('./transport.js');
    expect(transport.readPidFile()).toBeNull();
  });

  it('startDaemon on win32 writes address file', async () => {
    Object.defineProperty(process, 'platform', { value: 'win32' });
    const { startDaemon } = await import('./daemon.js');
    await startDaemon({ keepAlive: false, grpcPort: 0 });
    const transport = await import('./transport.js');
    expect(transport.readAddressFile()?.port).toBe(50051);
  });

  it('stopDaemon throws when no pid file', async () => {
    const { stopDaemon } = await import('./daemon.js');
    await expect(stopDaemon()).rejects.toThrow(/No daemon PID file/);
  });

  it('stopDaemon throws when process not running', async () => {
    const transport = await import('./transport.js');
    transport.ensureRuntimeDir();
    fs.writeFileSync(transport.getPidFilePath(), '999999999', { mode: 0o600 });
    const { stopDaemon } = await import('./daemon.js');
    await expect(stopDaemon()).rejects.toThrow(/not running/);
  });

  it('stopDaemon kills running process', async () => {
    const transport = await import('./transport.js');
    transport.writePidFile();
    const killSpy = vi.spyOn(transport, 'killDaemon').mockReturnValue(true);
    const { stopDaemon } = await import('./daemon.js');
    await stopDaemon();
    expect(killSpy).toHaveBeenCalled();
    killSpy.mockRestore();
  });

  it('stopDaemon throws when kill fails', async () => {
    const transport = await import('./transport.js');
    transport.writePidFile();
    const killSpy = vi.spyOn(transport, 'killDaemon').mockReturnValue(false);
    const { stopDaemon } = await import('./daemon.js');
    await expect(stopDaemon()).rejects.toThrow(/Failed to stop/);
    killSpy.mockRestore();
    transport.removePidFile();
  });

  it('bindTcpGrpc logs insecure and open-auth warnings', async () => {
    const grpcTls = await import('./grpc-tls.js');
    const consumerAuth = await import('./server/consumer-auth.js');
    vi.mocked(grpcTls.resolveTcpGrpcBind).mockReturnValue({
      tlsEnabled: false,
      serverCredentials: { type: 'insecure' },
      autoGenerated: false,
    } as never);
    vi.mocked(consumerAuth.buildConsumerAuthContext).mockReturnValue({ loopbackOnly: false } as never);
    vi.mocked(consumerAuth.hasConfiguredConsumers).mockReturnValue(false);
    vi.mocked(consumerAuth.resolveAllowOpenAuth).mockReturnValue(true);

    Object.defineProperty(process, 'platform', { value: 'linux' });
    const warnSpy = vi.spyOn(console, 'warn').mockImplementation(() => undefined);
    const { startDaemon } = await import('./daemon.js');
    await startDaemon({
      keepAlive: false,
      grpcPort: 50053,
      grpcHost: '0.0.0.0',
      grpcTls: { insecure: true },
      allowOpenAuth: true,
    });
    expect(warnSpy.mock.calls.some((c) => String(c[0]).includes('insecure'))).toBe(true);
    expect(warnSpy.mock.calls.some((c) => String(c[0]).includes('open consumer auth'))).toBe(true);
    warnSpy.mockRestore();
  });

  it('bindTcpGrpc logs TLS wildcard warning', async () => {
    const grpcTls = await import('./grpc-tls.js');
    const consumerAuth = await import('./server/consumer-auth.js');
    vi.mocked(grpcTls.resolveTcpGrpcBind).mockReturnValue({
      tlsEnabled: true,
      serverCredentials: { type: 'ssl' },
      autoGenerated: true,
      caPath: '/tmp/ca.crt',
    } as never);
    vi.mocked(consumerAuth.hasConfiguredConsumers).mockReturnValue(true);
    vi.mocked(consumerAuth.resolveAllowOpenAuth).mockReturnValue(false);

    Object.defineProperty(process, 'platform', { value: 'linux' });
    const warnSpy = vi.spyOn(console, 'warn').mockImplementation(() => undefined);
    const { startDaemon } = await import('./daemon.js');
    await startDaemon({
      keepAlive: false,
      grpcPort: 50054,
      grpcHost: '0.0.0.0',
      grpcTls: { enabled: true },
    });
    expect(warnSpy.mock.calls.some((c) => String(c[0]).includes('TLS is enabled'))).toBe(true);
    warnSpy.mockRestore();
  });
});
