/**
 * gRPC TLS credentials and TCP bind security policy.
 *
 * Policy (DR-029):
 * - Unix socket / named pipe: plaintext is fine (local IPC).
 * - TCP on loopback (127.0.0.1, ::1): plaintext allowed for local DX.
 * - TCP on non-loopback (incl. 0.0.0.0 / ::): requires TLS or explicit --insecure.
 */

import * as grpc from '@grpc/grpc-js';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';
import { getRuntimeDir } from '../core/paths.js';

/** Common Name used for auto-generated self-signed certs (and client name override). */
export const GRPC_TLS_DEFAULT_CN = 'abbenay-grpc';

export interface GrpcTlsOptions {
  /** Enable TLS with auto-generated self-signed certs. */
  enabled?: boolean;
  /** @internal Optional PEM paths for tests; production CLI uses auto-gen only. */
  certPath?: string;
  /** @internal Optional PEM paths for tests; production CLI uses auto-gen only. */
  keyPath?: string;
  /** @internal Optional CA path for tests. */
  caPath?: string;
  /** Allow plaintext on non-loopback binds (explicit opt-in). */
  insecure?: boolean;
}

export interface ResolvedGrpcTls {
  /** Whether the TCP listener uses TLS. */
  tlsEnabled: boolean;
  /** Server credentials for bindAsync. */
  serverCredentials: grpc.ServerCredentials;
  /** Absolute path to CA PEM clients should trust (when TLS enabled). */
  caPath?: string;
  /** Absolute path to server cert PEM. */
  certPath?: string;
  /** Absolute path to server key PEM. */
  keyPath?: string;
  /** Whether certs were auto-generated this run. */
  autoGenerated: boolean;
}

/**
 * True when the bind host is loopback-only (local DX plaintext OK).
 * Treats 127.0.0.1, ::1, and localhost as loopback. All other addresses
 * (including 0.0.0.0 / ::) are non-loopback.
 */
export function isLoopbackHost(host: string): boolean {
  const h = host.trim().toLowerCase();
  if (h === 'localhost' || h === '127.0.0.1' || h === '::1') {
    return true;
  }
  // IPv4-mapped IPv6 loopback
  if (h === '::ffff:127.0.0.1') {
    return true;
  }
  return false;
}

/**
 * True when the host binds all interfaces (wildcard).
 */
export function isWildcardHost(host: string): boolean {
  const h = host.trim().toLowerCase();
  return h === '0.0.0.0' || h === '::' || h === '[::]';
}

export class GrpcBindSecurityError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'GrpcBindSecurityError';
  }
}

/**
 * Enforce TCP bind security before listening.
 * Throws GrpcBindSecurityError when the bind would expose plaintext on a
 * non-loopback interface without an explicit insecure opt-in.
 */
export function assertTcpBindAllowed(
  host: string,
  opts: { tlsEnabled: boolean; insecure: boolean },
): void {
  if (isLoopbackHost(host)) {
    return;
  }

  if (opts.tlsEnabled) {
    return;
  }

  if (opts.insecure) {
    return;
  }

  const wildcardHint = isWildcardHost(host)
    ? ` Binding to ${host} exposes gRPC on all interfaces.`
    : '';

  throw new GrpcBindSecurityError(
    `Refusing to bind gRPC on non-loopback address "${host}" without TLS or --insecure.` +
      wildcardHint +
      ' Use --grpc-tls (auto self-signed) or pass --insecure to allow plaintext (not recommended).',
  );
}

/**
 * Resolve whether TLS should be enabled for a TCP bind given CLI/config options.
 * TLS is on when explicitly requested or when cert/key paths are provided.
 */
export function shouldEnableTls(opts: GrpcTlsOptions): boolean {
  if (opts.enabled) {
    return true;
  }
  if (opts.certPath || opts.keyPath) {
    return true;
  }
  return false;
}

/**
 * Generate a self-signed RSA certificate + key as PEM strings.
 * Pure Node.js (no openssl dependency) for SEA / container portability.
 */
export function generateSelfSignedPem(commonName: string = GRPC_TLS_DEFAULT_CN): {
  certPem: string;
  keyPem: string;
} {
  const { privateKey, publicKey } = crypto.generateKeyPairSync('rsa', {
    modulusLength: 2048,
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  });

  // Build a minimal self-signed X.509 v3 certificate.
  // Node does not ship a cert builder; we assemble DER manually for RSA-SHA256.
  const certPem = buildSelfSignedCertificate({
    privateKeyPem: privateKey,
    publicKeyPem: publicKey,
    commonName,
    days: 365,
  });

  return { certPem, keyPem: privateKey };
}

/**
 * Write auto-generated TLS material under the runtime directory.
 * Returns absolute paths. Permissions are restricted (dir 0700, key 0600).
 */
export function writeAutoTlsMaterial(
  runtimeDir: string = getRuntimeDir(),
  commonName: string = GRPC_TLS_DEFAULT_CN,
): { certPath: string; keyPath: string; caPath: string } {
  const tlsDir = path.join(runtimeDir, 'tls');
  fs.mkdirSync(tlsDir, { recursive: true, mode: 0o700 });

  const { certPem, keyPem } = generateSelfSignedPem(commonName);
  const certPath = path.join(tlsDir, 'server.crt');
  const keyPath = path.join(tlsDir, 'server.key');
  const caPath = path.join(tlsDir, 'ca.crt');

  fs.writeFileSync(certPath, certPem, { mode: 0o644 });
  fs.writeFileSync(keyPath, keyPem, { mode: 0o600 });
  // Self-signed: the server cert is also the trust anchor for clients.
  fs.writeFileSync(caPath, certPem, { mode: 0o644 });

  return { certPath, keyPath, caPath };
}

/**
 * Resolve TCP bind credentials after enforcing the security policy.
 * Asserts before any auto-cert filesystem side effects.
 */
export function resolveTcpGrpcBind(
  host: string,
  tlsOpts: GrpcTlsOptions = {},
): ResolvedGrpcTls {
  const wantTls = shouldEnableTls(tlsOpts);
  assertTcpBindAllowed(host, {
    tlsEnabled: wantTls,
    insecure: !!tlsOpts.insecure,
  });
  return createTcpServerCredentials(tlsOpts);
}

/**
 * Create gRPC server credentials for TCP (TLS or insecure).
 */
export function createTcpServerCredentials(opts: GrpcTlsOptions): ResolvedGrpcTls {
  const tlsEnabled = shouldEnableTls(opts);

  if (!tlsEnabled) {
    return {
      tlsEnabled: false,
      serverCredentials: grpc.ServerCredentials.createInsecure(),
      autoGenerated: false,
    };
  }

  let certPath = opts.certPath;
  let keyPath = opts.keyPath;
  let caPath = opts.caPath;
  let autoGenerated = false;

  if ((certPath && !keyPath) || (!certPath && keyPath)) {
    throw new GrpcBindSecurityError(
      'Both certPath and keyPath are required when providing custom certificates.',
    );
  }

  if (!certPath || !keyPath) {
    const generated = writeAutoTlsMaterial();
    certPath = generated.certPath;
    keyPath = generated.keyPath;
    caPath = caPath ?? generated.caPath;
    autoGenerated = true;
  } else {
    caPath = caPath ?? certPath;
  }

  const cert = fs.readFileSync(certPath);
  const key = fs.readFileSync(keyPath);

  return {
    tlsEnabled: true,
    serverCredentials: grpc.ServerCredentials.createSsl(null, [{ cert_chain: cert, private_key: key }], false),
    caPath: path.resolve(caPath),
    certPath: path.resolve(certPath),
    keyPath: path.resolve(keyPath),
    autoGenerated,
  };
}

/**
 * Create gRPC channel credentials for a client.
 * Unix sockets always use insecure. TCP uses SSL when caPath/tls is set.
 */
export function createClientCredentials(opts: {
  /** When true, use TLS (requires caPem or caPath for self-signed). */
  tls?: boolean;
  caPath?: string;
  caPem?: Buffer | string;
}): grpc.ChannelCredentials {
  if (!opts.tls && !opts.caPath && !opts.caPem) {
    return grpc.credentials.createInsecure();
  }

  let rootCerts: Buffer | null = null;
  if (opts.caPem) {
    rootCerts = typeof opts.caPem === 'string' ? Buffer.from(opts.caPem) : opts.caPem;
  } else if (opts.caPath) {
    rootCerts = fs.readFileSync(opts.caPath);
  }

  return grpc.credentials.createSsl(rootCerts);
}

/**
 * Channel options so clients accept auto-generated certs (CN = GRPC_TLS_DEFAULT_CN)
 * when connecting by IP / hostname that does not match the cert CN.
 */
export function grpcTlsChannelOptions(serverNameOverride: string = GRPC_TLS_DEFAULT_CN): Record<string, string> {
  return {
    'grpc.ssl_target_name_override': serverNameOverride,
    'grpc.default_authority': serverNameOverride,
  };
}

// ── Minimal self-signed X.509 builder (RSA-SHA256) ─────────────────────

function buildSelfSignedCertificate(params: {
  privateKeyPem: string;
  publicKeyPem: string;
  commonName: string;
  days: number;
}): string {
  const privateKey = crypto.createPrivateKey(params.privateKeyPem);
  const publicKey = crypto.createPublicKey(params.publicKeyPem);
  const spki = publicKey.export({ type: 'spki', format: 'der' }) as Buffer;

  const notBefore = new Date();
  const notAfter = new Date(notBefore.getTime() + params.days * 24 * 60 * 60 * 1000);
  const serial = crypto.randomBytes(8);

  // TBSCertificate
  const tbs = derSequence(
    Buffer.concat([
      // version v3 [0] EXPLICIT
      derContext(0, derInteger(Buffer.from([0x02]))),
      derInteger(serial),
      // signature algorithm
      sha256WithRsaEncryption(),
      // issuer
      derName(params.commonName),
      // validity
      derSequence(Buffer.concat([derUtcTime(notBefore), derUtcTime(notAfter)])),
      // subject
      derName(params.commonName),
      // subjectPublicKeyInfo (already DER)
      spki,
      // extensions [3] EXPLICIT — basicConstraints CA:true + SAN
      derContext(3, derSequence(Buffer.concat([
        basicConstraintsCa(),
        subjectAltName(params.commonName),
      ]))),
    ]),
  );

  const signature = crypto.sign('sha256', tbs, privateKey);

  const certDer = derSequence(
    Buffer.concat([
      tbs,
      sha256WithRsaEncryption(),
      derBitString(signature),
    ]),
  );

  return derToPem(certDer, 'CERTIFICATE');
}

function sha256WithRsaEncryption(): Buffer {
  // SEQUENCE { OID 1.2.840.113549.1.1.11, NULL }
  return Buffer.from('300d06092a864886f70d01010b0500', 'hex');
}

function basicConstraintsCa(): Buffer {
  // Extension: basicConstraints, critical, CA:TRUE
  const oid = Buffer.from('0603551d13', 'hex'); // 2.5.29.19
  const critical = Buffer.from('0101ff', 'hex'); // BOOLEAN TRUE
  const value = derOctetString(Buffer.from('30030101ff', 'hex')); // SEQUENCE { BOOLEAN TRUE }
  return derSequence(Buffer.concat([oid, critical, value]));
}

function subjectAltName(commonName: string): Buffer {
  // Extension: subjectAltName — DNS:commonName, DNS:localhost, IP:127.0.0.1
  const oid = Buffer.from('0603551d11', 'hex'); // 2.5.29.17
  const dnsCn = derContextPrimitive(2, Buffer.from(commonName, 'utf8')); // dNSName [2]
  const dnsLocal = derContextPrimitive(2, Buffer.from('localhost', 'utf8'));
  const ipLoopback = derContextPrimitive(7, Buffer.from([127, 0, 0, 1])); // iPAddress [7]
  const sanSeq = derSequence(Buffer.concat([dnsCn, dnsLocal, ipLoopback]));
  return derSequence(Buffer.concat([oid, derOctetString(sanSeq)]));
}

function derName(commonName: string): Buffer {
  // RDN SEQUENCE with CN (2.5.4.3) UTF8String
  const oidCn = Buffer.from('0603550403', 'hex');
  const cnValue = derUtf8String(commonName);
  const atv = derSequence(Buffer.concat([oidCn, cnValue]));
  const rdn = derSet(atv);
  return derSequence(rdn);
}

function derToPem(der: Buffer, label: string): string {
  const b64 = der.toString('base64');
  const lines = b64.match(/.{1,64}/g) ?? [];
  return `-----BEGIN ${label}-----\n${lines.join('\n')}\n-----END ${label}-----\n`;
}

function derSequence(content: Buffer): Buffer {
  return Buffer.concat([Buffer.from([0x30]), derLength(content.length), content]);
}

function derSet(content: Buffer): Buffer {
  return Buffer.concat([Buffer.from([0x31]), derLength(content.length), content]);
}

function derInteger(value: Buffer): Buffer {
  // Ensure positive integer (prepend 0x00 if high bit set)
  let v = value;
  if (v[0] & 0x80) {
    v = Buffer.concat([Buffer.from([0x00]), v]);
  }
  return Buffer.concat([Buffer.from([0x02]), derLength(v.length), v]);
}

function derBitString(bytes: Buffer): Buffer {
  const content = Buffer.concat([Buffer.from([0x00]), bytes]);
  return Buffer.concat([Buffer.from([0x03]), derLength(content.length), content]);
}

function derOctetString(bytes: Buffer): Buffer {
  return Buffer.concat([Buffer.from([0x04]), derLength(bytes.length), bytes]);
}

function derUtf8String(text: string): Buffer {
  const bytes = Buffer.from(text, 'utf8');
  return Buffer.concat([Buffer.from([0x0c]), derLength(bytes.length), bytes]);
}

function derUtcTime(date: Date): Buffer {
  // YYMMDDHHMMSSZ
  const yy = String(date.getUTCFullYear() % 100).padStart(2, '0');
  const mm = String(date.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(date.getUTCDate()).padStart(2, '0');
  const hh = String(date.getUTCHours()).padStart(2, '0');
  const mi = String(date.getUTCMinutes()).padStart(2, '0');
  const ss = String(date.getUTCSeconds()).padStart(2, '0');
  const s = `${yy}${mm}${dd}${hh}${mi}${ss}Z`;
  const bytes = Buffer.from(s, 'ascii');
  return Buffer.concat([Buffer.from([0x17]), derLength(bytes.length), bytes]);
}

/** Context-specific EXPLICIT (constructed) — e.g. version [0], extensions [3]. */
function derContext(tag: number, content: Buffer): Buffer {
  return Buffer.concat([Buffer.from([0xa0 | tag]), derLength(content.length), content]);
}

/** Context-specific IMPLICIT (primitive) — e.g. SAN dNSName [2], iPAddress [7]. */
function derContextPrimitive(tag: number, content: Buffer): Buffer {
  return Buffer.concat([Buffer.from([0x80 | tag]), derLength(content.length), content]);
}

function derLength(length: number): Buffer {
  if (length < 0x80) {
    return Buffer.from([length]);
  }
  if (length < 0x100) {
    return Buffer.from([0x81, length]);
  }
  if (length < 0x10000) {
    return Buffer.from([0x82, (length >> 8) & 0xff, length & 0xff]);
  }
  throw new Error(`DER length too large: ${length}`);
}
