---
name: push

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  ack:
    uses: ansible/team-devtools/.github/workflows/push.yml@main
